---
id: Lock
name: Lock
full: Resource locking library
description: A library that implements a resource locking system.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Lock
authors:
  -
    name: Ben Klang
    user: bklang
    email: ben@alkaloid.net
    active: true
    role: lead
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Support: ^2
  optional:
    pear:
      pear.horde.org/Horde_Db: ^2
      pear.horde.org/Horde_Log: ^2
      pear.horde.org/Horde_Mongo: ^1
