---
id: Lock
name: Lock
full: Resource locking library
description: A library that implements a resource locking system.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Lock
authors:
  -
    name: Ben Klang
    user: bklang
    email: ben@alkaloid.net
    active: true
    role: lead
version:
  release: 3.0.0alpha5
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1-only
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7.4 || ^8
    composer:
      horde/exception: ^3
      horde/support: ^3
  optional:
    composer:
      horde/db: ^3
      horde/log: ^3
      horde/mongo: ^2
